name: barteron.club

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: barteron.club
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Prepare
        run: |
          npm install --global yarn
          npx update-browserslist-db@latest
          yarn install
          yarn build
      - name: Copy
        run: |
          rm -rf /data/barteron/*
          rsync -ah ./dist/ /data/barteron/
        
